//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractID { get; set; }
        public string ContractType { get; set; }
        public int EmployeeID { get; set; }
        public int DepartmentID { get; set; }
        public int PositionID { get; set; }
        public double PayRate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Position Position { get; set; }
    }
}
