//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMenuDetail
    {
        public int DailyMenuID { get; set; }
        public int MealID { get; set; }
        public int DishID { get; set; }
        public bool Status { get; set; }
    
        public virtual DailyMenu DailyMenu { get; set; }
        public virtual Dish Dish { get; set; }
        public virtual Meal Meal { get; set; }
    }
}
