//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DailyMenu()
        {
            this.DailyMenuDetails = new HashSet<DailyMenuDetail>();
        }
    
        public int DailyMenuID { get; set; }
        public string Name { get; set; }
        public int WeeklyMenuID { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsForm { get; set; }
        public bool Status { get; set; }
    
        public virtual WeeklyMenu WeeklyMenu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyMenuDetail> DailyMenuDetails { get; set; }
    }
}
