//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Class
    {
        public int EmployeeID { get; set; }
        public int ClassID { get; set; }
        public bool Status { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
