//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodGroup
    {
        public int FoodGroupID { get; set; }
        public string Name { get; set; }
        public double MinKcal { get; set; }
        public double MaxKcal { get; set; }
        public bool Status { get; set; }
    }
}
