//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthProblem
    {
        public int HealthProblemID { get; set; }
        public int StudentID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Signal { get; set; }
        public string Diagnosed { get; set; }
        public string Measure { get; set; }
        public int Serverity { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }
    }
}
