//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealthExamination
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealthExamination()
        {
            this.HealthExaminationDetails = new HashSet<HealthExaminationDetail>();
        }
    
        public int HealthExaminationID { get; set; }
        public System.DateTime Date { get; set; }
        public string Name { get; set; }
        public string Place { get; set; }
        public bool Height { get; set; }
        public bool Weight { get; set; }
        public bool Eyes { get; set; }
        public bool ENT { get; set; }
        public bool InternalMedicine { get; set; }
        public bool Oral { get; set; }
        public bool Surgery { get; set; }
        public bool Dermatology { get; set; }
        public bool BoneMuscle { get; set; }
        public bool Nerve { get; set; }
        public bool Endocrine { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthExaminationDetail> HealthExaminationDetails { get; set; }
    }
}
