//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public int IngredientID { get; set; }
        public decimal PriceOfUnit { get; set; }
        public int QuantityOfUnit { get; set; }
        public decimal TotalPrice { get; set; }
        public byte Discount { get; set; }
        public bool Status { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Order Order { get; set; }
    }
}
