//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLHSBanTruEntities : DbContext
    {
        public QLHSBanTruEntities()
            : base("name=QLHSBanTruEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<CourseTask> CourseTasks { get; set; }
        public virtual DbSet<DailyMenu> DailyMenus { get; set; }
        public virtual DbSet<DailyMenuDetail> DailyMenuDetails { get; set; }
        public virtual DbSet<DailyTask> DailyTasks { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Dish> Dishes { get; set; }
        public virtual DbSet<DishDetail> DishDetails { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Employee_Class> Employee_Class { get; set; }
        public virtual DbSet<Employee_Function> Employee_Function { get; set; }
        public virtual DbSet<EthnicGroup> EthnicGroups { get; set; }
        public virtual DbSet<FoodGroup> FoodGroups { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<FunctionGroup> FunctionGroups { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<HealthExamination> HealthExaminations { get; set; }
        public virtual DbSet<HealthExaminationDetail> HealthExaminationDetails { get; set; }
        public virtual DbSet<HealthProblem> HealthProblems { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Ingredient> Ingredients { get; set; }
        public virtual DbSet<IngredientType> IngredientTypes { get; set; }
        public virtual DbSet<Lesson> Lessons { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<PhysicalMonthlyTask> PhysicalMonthlyTasks { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<Preferred> Preferreds { get; set; }
        public virtual DbSet<Receivable> Receivables { get; set; }
        public virtual DbSet<ReceivableDetail> ReceivableDetails { get; set; }
        public virtual DbSet<ReceivableDetail_Preferred> ReceivableDetail_Preferred { get; set; }
        public virtual DbSet<ReceivableDetail_Student> ReceivableDetail_Student { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Revenue> Revenues { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Student_Class> Student_Class { get; set; }
        public virtual DbSet<Student_Lesson> Student_Lesson { get; set; }
        public virtual DbSet<StudentParent> StudentParents { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<TopicType> TopicTypes { get; set; }
        public virtual DbSet<WeeklyMenu> WeeklyMenus { get; set; }
        public virtual DbSet<WeeklyTask> WeeklyTasks { get; set; }
    }
}
