//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivableDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceivableDetail()
        {
            this.ReceivableDetail_Preferred = new HashSet<ReceivableDetail_Preferred>();
            this.ReceivableDetail_Student = new HashSet<ReceivableDetail_Student>();
        }
    
        public int ReceivableDetailID { get; set; }
        public int ReceivableID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public decimal SalePrice { get; set; }
        public bool Status { get; set; }
        public Nullable<int> RevenueID { get; set; }
    
        public virtual Receivable Receivable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivableDetail_Preferred> ReceivableDetail_Preferred { get; set; }
        public virtual Revenue Revenue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivableDetail_Student> ReceivableDetail_Student { get; set; }
    }
}
