//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivableDetail_Student
    {
        public int ReceivableDetailID { get; set; }
        public int StudentID { get; set; }
        public bool Status { get; set; }
    
        public virtual ReceivableDetail ReceivableDetail { get; set; }
        public virtual Student Student { get; set; }
    }
}
