//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.CourseTasks = new HashSet<CourseTask>();
            this.DailyTasks = new HashSet<DailyTask>();
            this.HealthExaminationDetails = new HashSet<HealthExaminationDetail>();
            this.HealthProblems = new HashSet<HealthProblem>();
            this.ReceivableDetail_Student = new HashSet<ReceivableDetail_Student>();
            this.Student_Class = new HashSet<Student_Class>();
            this.Student_Lesson = new HashSet<Student_Lesson>();
            this.StudentParents = new HashSet<StudentParent>();
        }
    
        public int StudentID { get; set; }
        public string StudentCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HomeName { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Gender { get; set; }
        public byte[] Image { get; set; }
        public string Hobby { get; set; }
        public string Talent { get; set; }
        public int EthnicGroupID { get; set; }
        public int ReligionID { get; set; }
        public int BirthPlaceID { get; set; }
        public int LocationID { get; set; }
        public string AdressDetail { get; set; }
        public Nullable<int> PreferredID { get; set; }
        public string Note { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseTask> CourseTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyTask> DailyTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthExaminationDetail> HealthExaminationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HealthProblem> HealthProblems { get; set; }
        public virtual Location Location { get; set; }
        public virtual Preferred Preferred { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivableDetail_Student> ReceivableDetail_Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Class> Student_Class { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Lesson> Student_Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentParent> StudentParents { get; set; }
    }
}
