//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_QLHSBanTru.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentParent
    {
        public int StudentParentsID { get; set; }
        public int StudentID { get; set; }
        public string Password { get; set; }
        public string FatherName { get; set; }
        public System.DateTime FatherBirthday { get; set; }
        public string FatherPhone { get; set; }
        public string FatherJob { get; set; }
        public string MotherName { get; set; }
        public System.DateTime MotherBirthday { get; set; }
        public string MotherPhone { get; set; }
        public string MotherJob { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
